### ISSUE TITLE
indoor scene

### ISSUE THREAD

**Issue by betterze** [genforce/idinvert#3]
Thanks for your work. It is a very nice paper. I have a simple question.

Have you try this method on indoor image? For example, in [higan](https://github.com/genforce/higan ), which also comes from your group, it show manipulation for indoor images. Do you think [idinvert](https://github.com/genforce/higan ) could invert indoor images and do the same manipulation as [higan](https://github.com/genforce/higan )? 

Thank you for your help.

**Comment by zhujiapeng** [comment]
We released a bedroom pre-trained model, which is an indoor scene image and we also added some manipulation results on the bedroom in the Appendix.  As far as I know, it is very hard that the manipulation results on the real image could reach the manipulation results on the synthesis image.

**Comment by zhujiapeng** [comment]
We released a bedroom pre-trained model, which is an indoor scene image and we also added some manipulation results on the bedroom in the Appendix.  The [idinvert](https://github.com/genforce/idinvert/issues/1) could do the same manipulation as [higan](https://github.com/genforce/higan) but the results may not as good as [higan](https://github.com/genforce/higan) since it is very hard that the manipulation results on the real image could reach the manipulation results on the synthesis image.
