### ISSUE TITLE
How to obtain projected direction given pretained boundaries?

### ISSUE THREAD

**Issue by fungtion** [genforce/idinvert#33]
I tried to get age/eyeglass boundry using the method discribed in the paper "interfacegan", e.g. _n = n_age - (n_age^T * n_eyeglass) * n_eyeglass_ with the boundary file age.npy and glass.npy provided, but when I manipute age/eyeglasses attribute, the  images hardly changed as expected. If there is any difference when manipulating w and wp?

**Comment by ShenYujun** [comment]
This phenomenon is discussed in InterFaceGAN, which is that conditional manipulation does work well on StyleGAN `W` space. The reason is that all boundaries in the `W` space are already orthogonal. You can verify this by measuring the similarity between *n* and *n_age* you've mentioned. They should be very close to each other.

**Comment by fungtion** [comment]
Thanks. Is that means better distanglement in w space leads to the orthogonal boundaries?

**Comment by ShenYujun** [comment]
Yes. But the disentanglement in `W` space is not perfect. That is why the entanglement between "eyeglasses" and "age" can still be observed. How to find more disentangled boundaries is still worth exploring.

**Comment by fungtion** [comment]
I see, thank you.
